### ISSUE TITLE
Transfer of mizer to https://github.com/sizespectrum

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#11]
Hi Finlay, you indicated that you wanted someone to adopt mizer.  I have created an 'organisation' called 'sizespectrum' and have invited you as an owner. You could transfer the mizer project to that organisation and in that way you can share the maintainership of mizer with others, including me. What do you think? For how to effect a transfer, see https://help.github.com/articles/transferring-a-repository/

**Comment by drfinlayscott** [comment]
Hi Gustav,
Apologies for the late reply. I am in the middle of packing up my house in
Italy. I have had a change of plan and will be staying at the JRC for a
while longer yet. However, the change in contract requires me to take a
break over the summer and I will not back at the JRC until September at the
earliest. Tomorrow I am returning to the UK and will be fairly nomadic over
the next couple of months.

I like the idea of the sizespectrum organisation as I do not think my new
role will allow me much time to focus on mizer. I know that there other
parties, including Ken Andersen and Julia Blanchard, who are also
interested in developing mizer. It could be a good idea to have all these
developments in one place. I'll let them know and maybe we can organise
coordinated development.

Yours

Finlay

**Comment by gustavdelius** [comment]
Hi Finlay, 

many thanks for effecting this transfer. It will make the long-term maintenance easier and preserve your legacy.

Best,
Gustav

**Comment by drfinlayscott** [comment]
"preserve my legacy" :)
Makes it sound like a Nobel prize winning bit of work instead of an
implementation of ideas from Ken's brain
