### ISSUE TITLE
summary() for MizerParams objects returns length of w_full as number of plankton bins

### ISSUE THREAD

**Issue by patricksykes** [sizespectrum/mizer#116]
When calling the `summary()` function on a MizerParams object, I think the number of size bins in the plankton spectrum should refer to the number of non-empty bins (i.e. the number of bins containing plankton), not the length of the complete size spectrum `w_full`.

See https://github.com/patricksykes/mizer/commit/7b8ebbcb9c6bcf53a762128043839b4037e2464a for how I think this might be improved.

**Comment by gustavdelius** [comment]
I agree. Thanks Patrick. Please create a pull request for that change.
