### ISSUE TITLE
The carrying capacity of resource spectrum

### ISSUE THREAD

**Issue by QinqinLin** [sizespectrum/mizer#133]
I want to apply this model to an ocean ecosystem.  I try to evaluate the response of some important economic species to fishing. Most species in the simulation study are pelagic predators. Data about the background resources (initial_n_pp)  in the open ocean is difficult to obtain and I don't know how to estimate this parameter (carrying capacity).  Many thanks!

**Comment by Kenhasteandersen** [comment]
Dear Quinqin,

Good question. The level of the background resources essentially determines the total biomass of fish. You can therefore adjust that parameter until you obtain a biomass (or a biomass spectrum) of fish that matches what you observe. You can also follow the calibration procedure in appendix B of the attached paper. Please write again if you have problems.

Ken
[Jacobsen et al (2016).pdf](https://github.com/sizespectrum/mizer/files/4025416/Jacobsen.et.al.2016.pdf)

**Comment by QinqinLin** [comment]
Thanks, Ken! I will try these two methods. And I am wondering if you could send me the relevant code about the calibration procedure as a reference?


Best,
Qinqin


On 1/6/2020 17:15，Kenhasteandersen<notifications@github.com> wrote：

Dear Quinqin,

Good question. The level of the background resources essentially determines the total biomass of fish. You can therefore adjust that parameter until you obtain a biomass (or a biomass spectrum) of fish that matches what you observe. You can also follow the calibration procedure in appendix B of the attached paper. Please write again if you have problems.

Ken
Jacobsen et al (2016).pdf

**Comment by Kenhasteandersen** [comment]
I don't have a code to do this on mizer (I used my own code when I did it). The development version of mizer has interactive tuning tools. You can try them as well: https://sizespectrum.org/mizer/dev/reference/index.html

Ken

**Comment by QinqinLin** [comment]
Thanks, I really appreciate it.


Best, 
Qinqin


On 1/7/2020 14:35，Kenhasteandersen<notifications@github.com> wrote：

I don't have a code to do this on mizer (I used my own code when I did it). The development version of mizer has interactive tuning tools. You can try them as well: https://sizespectrum.org/mizer/dev/reference/index.html

Ken

**Comment by gustavdelius** [comment]
@QinqinLin , unless you have information about the abundance of the resource, it makes sense to assume that it is such properly support the fish community. You can see an example of setting up a model without knowledge of the resource abundance in the mizer blog at https://blog.mizer.sizespectrum.org/posts/2021-08-20-a-5-step-recipe-for-tuning-the-model-steady-state/. Don't hesitate to get in touch when you have further questions about that.
