### ISSUE TITLE
Strange naming choices

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#156]
As you look at the documentation of the new version of mizer and start working with it, you will find that some names are very strangely chosen and should be changed. Some choices are of course historical and can not easily be changed without breaking backwards compatibility. Others however I simply introduced by mistake in this new version. Please add your observations to this issue so that we can change the names before the new version becomes too widely known. Here are some I am aware of and suggested solutions. Please comment.

- [x]  `interaction_p` is the column in the species data frame that determines the strength with which a species feeds on the resource. `resource_interaction` might be a better name.

- [x] The pair `r_resource` and `getResourceRate()` does not go well together. The variable should perhaps be called `resource_rate`.

- [x] Similarly `K_resource` and `getResourceCapacity()` don't go well together. The variable should perhaps be `resource_capacity`.

**Comment by Kenhasteandersen** [comment]
*    interaction_p is the column in the species data frame that determines the strength with which a species feeds on the resource. resource_interaction might be a better name.

Fine. Or refer to “interaction” first, like interactionResource ?

  *   [] The pair r_resource and getResourceRate() does not go well together. The variable should perhaps be called resource_rate.

Indeed.

  *   [] Similarly K_resource and getResourceCapacity() don't go well together. The variable should perhaps be resource_capacity.

Yes.

Ken


  *

**Comment by gustavdelius** [comment]
I chose `interaction_resource`. The convention is to use underscores in variable names and CamelCase in function names. An exception is made for some assessor functions, like `resource_params()`.
