### ISSUE TITLE
Selectivity and catchability by defining their values directly

### ISSUE THREAD

**Issue by michaelspence** [sizespectrum/mizer#172]
I have run into a few issues when creating several fleets by choosing their selectivity and catchability. When I manipulate a created selectivity and catchability matrix it works fine however when I create it by specifying the selectivity and catchability directly it does not. I demonstrate the problem below:

First I remove gears and create a `params` object:
`library(mizer)`
`NS_species <- NS_species_params_gears`
`NS_species <- dplyr::select(NS_species, -gear)`
`params_tmp <- newMultispeciesParams(NS_species,inter) ## used to get selectivity and catchbility`

then I manipulate the `selectivity` and `catchability` by adding a new fleet
`selectivity <- params_tmp@selectivity`
`selectivity <- abind(selectivity,array(0.5,dim=c(1,12,100)),along=1)`
`dimnames(selectivity)[[1]] <- c("knife_edge_gear","other")`
`catchability <- params_tmp@catchability`
`catchability <- rbind(catchability,1)`
`rownames(catchability)[2] <- "other"`

I test it and it works perfectly
`params <- newMultispeciesParams(NS_species,inter,selectivity = selectivity, catchability = catchability)`
`effort <- matrix(0.5,10,2,dimnames = list(1:10,c("knife_edge_gear","other")))`
`run <- project(params,effort=effort)`

Now I try and do the same thing by first creating the selectivity and catchability
`N_gear <- 13`
`selectivity1 <- array(0.5,c(N_gear,12,100),dimnames=list(gear=paste("gear",1:N_gear,sep="_"),sp=NS_species$species,w=params_tmp@w))`
`catchability1 <- apply(selectivity1,c(1,2),function(x){1*any(x>0)})`
and build a the `MizerParams` object
`params <- newMultispeciesParams(NS_species,inter,selectivity = selectivity1, catchability = catchability1)`
which gives this error 
`Error in validObject(params) : invalid class “MizerParams” object: The size names of psi, intake_max, search_vol, metab and selectivity must all be the same`
Doing it using `setFishing()` gives a similar error
`params <- newMultispeciesParams(NS_species,inter)`
`params <- setFishing(params,selectivity = selectivity1, catchability = catchability1)`
`effort <- matrix(0.5,10,N_gear,dimnames = list(1:10,paste("gear",1:N_gear,sep="_")))`
 but only when using `project`
`run <- project(params,effort=effort)`
`Error in validObject(params) : invalid class “MizerParams” object: The size names of psi, intake_max, search_vol, metab and selectivity must all be the same`
I presume the error is in `validObject(params)` but I haven't investigated it further. That said I don't think I understand why it worked the first time.

**Comment by michaelspence** [comment]
The issue goes away when you redefine the name of the weights:
`selectivity1 <- array(0.5,c(N_gear,12,100),dimnames=list(gear=paste("gear",1:N_gear,sep="_"),sp=NS_species$species,w=dimnames(params_tmp@selectivity)[[3]]))`
or
`selectivity1 <- array(0.5,c(N_gear,12,100),dimnames=list(gear=paste("gear",1:N_gear,sep="_"),sp=NS_species$species,w=signif(params_tmp@w,3)))`
That is setting the names of the 3rd dimension of the selectivity array to be the same as before `dimnames(params_tmp@selectivity)[[3]]` or the weights to 3 significant figures `signif(params_tmp@w,3)`. I think this comes from the `sweep` function. 

It's not really a problem anymore, sorry about the title, but took some digging to find the solution.

**Comment by gustavdelius** [comment]
Thank you for the detailed report. As you say, the problem is that your code sets the wrong dimnames for the size dimension. I suspect it would help if the error message was improved to spell out more clearly what the required dimnames are. Also the validity should be checked already in `setFishing()`. Perhaps `setFishing()` should actually fix the dimnames itself and just issue a warning.

**Comment by gustavdelius** [comment]
`setFishing()` now throws appropriate errors or warnings when the dimnames on the catchability or selectivity arrays are wrong.
