### ISSUE TITLE
Starvation mortality not implemented

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#23]
While equation (3.13) in the mizer vignette says that when food supply is insufficient to cover the cost of metabolism and movement there is starvation mortality, no such starvation mortality is implemented in the mizer code. Shall we just state clearly in the vignette that it is not implemented?

**Comment by Kenhasteandersen** [comment]
Seems reasonable; it is important that the vignette represents what is (and is not) in the code!

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk

New online app: Fish community simulator http://oceanlife.dtuaqua.dk/cspectrum.

[cid:image001.jpg@01D09493.A377DFB0]

On 7 Dec 2017, at 19.53, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


While equation (3.13) in the mizer vignette says that when food supply is insufficient to cover the cost of metabolism and movement there is starvation mortality, no such starvation mortality is implemented in the mizer code. Shall we just state clearly in the vignette that it is not implemented?

**Comment by gustavdelius** [comment]
Thanks Ken. The vignette is now updated to acknowledge that starvation death is not implemented in mizer.

**Comment by gustavdelius** [comment]
Starvation mortality has now been implemented
