### ISSUE TITLE
Drop the requirement that interaction matrix entries are between 0 and 1

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#232]
This restriction is totally unnecessary and can be inconvenient. For example if a user starts with the default interaction matrix with all entries equal to 1 and then wants to increase the interaction between a pair of species, currently they have to instead decrease the interaction between all other pairs and then increase `gamma`. Very inconvenient and for no good reason.

**Comment by drfinlayscott** [comment]
Is it inconvenient? I think it was originally set up as a proportion, i.e.
what proportion of the stock overlaps with another stock. Scaling it
between 0 and 1 makes sense to me. If the values can be 0 - X, what does it
measure?

**Comment by gustavdelius** [comment]
Hi Finlay. It would not measure anything in particular but rather allow the user to adjust the relative strength of interaction, similar to how the fishing effort does not measure anything but allows the user to adjust the relative strength of fishing. The user could still use the interaction matrix for proportional overlap if that is appropriate in their application. 

There is a problem however with using the interaction matrix as a way to capture spatial variations in density. The way mizer currently determines encounter rates assumes that the abundance is uniformly distributed spatially. Otherwise there would be higher spatial densities in some regions and this should lead to higher encounter rates, and in order to take that into account one would have to increase gamma. Then gamma would no longer represent just something about the predator's search volume but also something about the prey's spatial density. Nothing wrong with that, I am just bringing it up to say that using the interaction matrix is not an entirely straightforward way to take spatial effects into account in any way, no matter whether it is representing proportions or not.

**Comment by drfinlayscott** [comment]
Hi,
Yeah, that interaction matrix was a very rudimentary way of trying to
include spatial effects.

Cheers
