### ISSUE TITLE
Set initial effort to 1

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#243]
When setting up a new model with `newMultispeciesParams()` it is easy to forget to turn on the fishing effort because the default is 0. A more convenient default for the effort would be 1, because it is rare to set up a model for a system without fishing.

**Comment by Kenhasteandersen** [comment]
An effort of 1/year is too high. 0.3/year is more appropriate.

**Comment by gustavdelius** [comment]
Hi Ken. As you know, the value of the effort is up to convention. Effort = 1 means fishing mortality = catchability. That is a convenient convention. The default for the catchability will stay at 0.

**Comment by gustavdelius** [comment]
Thanks to Ken's suggestion I have now settled on the new default values of `catchability = 0.3` and `effort = 1`.
