### ISSUE TITLE
Starvation mortality 

### ISSUE THREAD

**Issue by astaaudzi** [sizespectrum/mizer#37]
It is suggested that starvation mortality should be added, as indicated in the original mizer vingette, and in Hartvig and Andersen (2013, Theoretical Population Ecology). 

This is now added as a pull request in the mizer development branch. 

The starvation mortality is calculated at each time step and each size class and is defined as: 
0, if e (assimilated intake - maintenance) >= 0 
- e/ 0.1*m, if e <0 
The value 0.1 is just a fixed parameter, following Hartvig and Andersen (2013), used a proportionality constant or reserve proportion in total weight (assumed to be fixed for all size classes). Such formulation leads to instantaneous starvation mortality of 1 if energy deficit is 10% of the total body weight. 

Currently in mizer negative e values are converted to 0 to ensure there is negative growth. 
In the version with starvation mortality, this is still the case, but negative e values add an extra starvation mortality term

**Comment by gustavdelius** [comment]
I have decided to move starvation mortality out of core mizer and into an extension package, see https://github.com/sizespectrum/mizerStarvation
