### ISSUE TITLE
Allow feeding kernel to be kept in MizerParams object even when using FFT method

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#40]
There is a desire, expressed by @juliablanchard and @astaaudzi to have convenient access to the full feeding kernel array (predator species x predator size x prey size) even when the model uses a constant predator/prey mass ratio, so that the information in the array is highly redundant. Having this array simplifies the calculation of diets, for example.

The proposal is to introduce a parameter to the functions for setting up MizerParams objects that is a flag determining whether to keep the full feeding kernel around. By default this is set to TRUE when the number of size classes is no more than 200 and to FALSE otherwise. The reason to set the default to FALSE when using more than 200 size classes is that the array then takes up substantial amount of storage.

**Comment by astaaudzi** [comment]
The full feeding kernel would be useful for cases where species are expected to have variable PPMR with size. This applies to planktivorous fish, that feed on small prey even when they grow large. Same is true for many coastal benthivorous fish, which are dominant species in e.g. Tasmanian coastal model. 
The method we are trying to implement is published in Heneghan et al. 2016 (http://journal.frontiersin.org/article/10.3389/fmars.2016.00201/abstract) and only requires one extra parameter _m_. The code is more or less implemented in https://github.com/astaaudzi/mizer-rewiring (although the final version has not been pushed yet). We are just waiting for the resolution on the differences between different integration method for the feeding kernel (issue #39)

**Comment by gustavdelius** [comment]
@astaaudzi this issue is specifically about keeping the feeding kernel around also when the PPMR is not variable. When the PPMR is variable, then of course the feeding kernel needs to be kept around because it is then needed to calculate the feeding and mortality rates because the FFT method can not be used. I will therefore split your comment into a new issue #41

**Comment by astaaudzi** [comment]
Yes, I agree. 
@reum has developed useful codes and plots to track diets across species and sizes, where the full kernel is useful (although diet composition plots might be a yet another issue? :) )

**Comment by gustavdelius** [comment]
You can now keep the feeding kernel around by passing `store_kernel = TRUE` to MizerParams. By default the kernel is kept when there are 100 or fewer size bins.
