### ISSUE TITLE
How to define spawning stock biomass

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#47]
Mizer has a function [getSSB(sim)](http://gustavdelius.github.io/mizer/reference/getSSB.html) that according to its documentation "Calculates the spawning stock biomass (SSB) through time of the species in the MizerSim class. SSB is calculated as the total mass of all mature individuals."

So it should multiply the total abundance by the maturity ogive (giving the proportion of individuals at size that are mature) and integrate over sizes. In practice however, it multiplies not by the proportion of individuals that are mature but by the proportion psi of the energy available for growth and reproduction that is put into reproduction. Thus it underestimates the spawning stock biomass quite substantially.

I propose that we split psi into its two factors, the maturity ogive giving the proportion of mature individuals (a sigmoidal function) and the reproduction allocation function that gives the proportion of the energy that a mature individual invests into reproduction (a power law). Then we can calculate the SSB properly which will make it easier to compare the mizer model output to observations of SSB.

I am posting this here in case I misunderstood what people mean by SSB.

**Comment by Kenhasteandersen** [comment]
So it should multiply the total abundance by the maturity ogive (giving the proportion of individuals at size that are mature) and integrate over sizes. In practice however, it multiplies not by the proportion of individuals that are mature but by the proportion psi of the energy available for growth and reproduction that is put into reproduction. Thus it underestimates the spawning stock biomass quite substantially.

You are right. The SSB should be calculated by multiplying with the maturity ogive, and not with psi. You write that the integration is over abundance, but it should be over biomass:

SSB = integral N(w)*w*psi_mature(w) dw

where psi_mature(w) is the fraction of individuals mature.

This is an error that should be fixed.

Ken



I propose that we split psi into its two factors, the maturity ogive giving the proportion of mature individuals (a sigmoidal function) and the reproduction allocation function that gives the proportion of the energy that a mature individual invests into reproduction (a power law). Then we can calculate the SSB properly which will make it easier to compare the mizer model output to observations of SSB.

I am posting this here in case I misunderstood what people mean by SSB.

**Comment by juliablanchard** [comment]
I agree (and that’s also how we calculated it the North Sea papers when we compared to SSB).

I actually can’t remember why it was set up differently in getSSB() in mizer ...


________________________________

**Comment by gustavdelius** [comment]
Thanks for the comments. I will fix that. (By the way: the confusion between abundance and biomass was just mine when I wrote the post, the code does not make that stupid mistake. But it does use psi as a factor instead of the maturity ogive.)
