### ISSUE TITLE
Website with package documentation

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#48]
We have started to built a website with the mizer documentation. You can view its current state at http://gustavdelius.github.io/mizer/ . There is clearly much scope for improvement, but I think it is already useful. Do we want that kind of website for the official mizer?

We used the pkgdown package to create the website. This means it is created from the content in the github repository itself, making it easy for people to contribute. I have started to document how to develop the website at http://gustavdelius.github.io/mizer/articles/editing_website.html. There is also a "Edit this page" link at the top of most pages which allow anyone to suggest edits (this works via github pull requests).

**Comment by Kenhasteandersen** [comment]
Dear Gustav,

I think the page looks very professional. Clear and to the point. Wonderful.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New paper: A trait-based approach to ocean ecology<https://www.google.com/url?q=https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsy090/5056134&sa=D&sntz=1&usg=AFQjCNFVkw1WnenGUFvOaKHEPxp8I30XKA>. ICES Journal of Marine Science 2, 65–70 (2018)

[cid:image001.jpg@01D09493.A377DFB0]

On 3 Apr 2019, at 10.51, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


We have started to built a website with the mizer documentation. You can view its current state at http://gustavdelius.github.io/mizer/ . There is clearly much scope for improvement, but I think it is already useful. Do we want that kind of website for the official mizer?

We used the pkgdown package to create the website. This means it is created from the content in the github repository itself, making it easy for people to contribute. I have started to document how to develop the website at http://gustavdelius.github.io/mizer/articles/editing_website.html. There is also a "Edit this page" link at the top of most pages which allow anyone to suggest edits (this works via github pull requests).

**Comment by astaaudzi** [comment]
I agree! The page is great and very well made. 
a

**Comment by gustavdelius** [comment]
The website is now live at https://sizespectrum.github.io/mizer/. This is the documentation for the released version of mizer. 

Ken (@Kenhasteandersen ), you own the domain mizer.info, I believe. Do you want to set it to point to the new website? 

I propose that in future we follow the standard convention that the development code lives in the master branch. In preparation for that I have already created a version1.0.1 branch with the released version. Once we have moved the development code to the master branch the website for the development version will be at https://sizespectrum.github.io/mizer/dev/

**Comment by juliablanchard** [comment]
Excellent Gustav!

Sent from my iPhone

________________________________

**Comment by Kenhasteandersen** [comment]
Perfect. I’ll make sure to point mizer.info<http://mizer.info> to the page.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New paper: A trait-based approach to ocean ecology<https://www.google.com/url?q=https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsy090/5056134&sa=D&sntz=1&usg=AFQjCNFVkw1WnenGUFvOaKHEPxp8I30XKA>. ICES Journal of Marine Science 2, 65–70 (2018)

[cid:image001.jpg@01D09493.A377DFB0]

On 7 Apr 2019, at 20.15, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


The website is now live at https://sizespectrum.github.io/mizer/. This is the documentation for the released version of mizer.

Ken (@Kenhasteandersen<https://github.com/Kenhasteandersen> ), you own the domain mizer.info<http://mizer.info>, I believe. Do you want to set it to point to the new website?

I propose that in future we follow the standard convention that the development code lives in the master branch. In preparation for that I have already created a version1.0.1 branch with the released version. Once we have moved the development code to the master branch the website for the development version will be at https://sizespectrum.github.io/mizer/dev/

**Comment by gustavdelius** [comment]
Thanks @Kenhasteandersen , let me know when you have done that and I will tell Github and CRAN about the new URL

**Comment by gustavdelius** [comment]
The website for the development version of mizer is now at <https://sizespectrum.github.io/mizer/dev/> (and will be at <https://mizer.info/dev/> soon).
