### ISSUE TITLE
Functions for changing model parameters

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#51]
One thing that I found really difficult to figure out when I was new to mizer was how to change the parameters in a model after I had set it up. Sometimes changing the species parameters in the MizerParams object would work, sometimes it would have no effect. In order to save future users from similar confusion, I would like to introduce a function `changeParams()` that users can call after changing a species parameter to change the model accordingly. So for example they could do:
```
params <- set_trait_model()
params@species_params$gamma[3] <- 1000
params <- changeParams(params)
```
and the result would be a model with an appropriately changed search volume.

Another thing that I found difficult to find out without looking very closely at the code documentation was whether some particular assumption about the form of some model function, like the allometric scaling assumptions for example, was hardwired into mizer or was something I could overrule. I therefore gave the `changeParams()` function additional arguments that allow the user to set up the most general mizer model possible. 

Please take a look at http://gustavdelius.github.io/mizer/reference/changeParams.html to see the details of what I am proposing. I have split the overall `changeParams()` function into several smaller functions changing particular aspects of the model. I may not have made very good choices for the names of the functions, so any suggestions for changes will be appreciated.

Besides the benefit to new users, the introduction of these functions also makes the code much easier to work with, because they do not need to wade through the complicated old MizerParams() code to find where a particular slot was set up but can go directly to the appropriate function, because MizerParams() also uses these functions to fill the slots in the MizerParams object. Furthermore it is easier to know where to document the setting of the various parameters, because this can now go into the documentation of the appropriate function.

**Comment by gustavdelius** [comment]
I have difficulties deciding whether the names of these functions should start with "set" or with "change". What comes more natural to you: `setPredKernel` or `changePredKernel`? 
Can you please take a look at the names of these functions in general (you see them all listed here: <https://sizespectrum.github.io/mizer/dev/reference/changeParams.html>) and make suggestions for changes?

**Comment by Kenhasteandersen** [comment]
Hi Gustav,

“set” would be more natural to me, however, both work fine.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New paper: A trait-based approach to ocean ecology<https://www.google.com/url?q=https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsy090/5056134&sa=D&sntz=1&usg=AFQjCNFVkw1WnenGUFvOaKHEPxp8I30XKA>. ICES Journal of Marine Science 2, 65–70 (2018)

[cid:image001.jpg@01D09493.A377DFB0]

On 16 Apr 2019, at 8:58 , Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


I have difficulties deciding whether the names of these functions should start with "set" or with "change". What comes more natural to you: setPredKernel or changePredKernel?
Can you please take a look at the names of these functions in general (you see them all listed here: https://sizespectrum.github.io/mizer/dev/reference/changeParams.html) and make suggestions for changes?

**Comment by gustavdelius** [comment]
I also find "set" more natural. Will change that now.
