### ISSUE TITLE
plotYieldCurve()

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#53]
Mizer should have a function for plotting the yield curve. @Kenhasteandersen mentioned that he found the yield curve to be useful while calibrating a model. Ken, do you have code to share for plotting the yield curve in mizer?

**Comment by Kenhasteandersen** [comment]
Ken, do you have code to share for plotting the yield curve in mizer?

Not really. It should be straight-forward: the function should take the result of a simulation and a vector of the species for which to make the yield curves. It should then run through each of the species, and for each species calculate yield for fishing mortalities in the range of, say, 0 to 2.

Ken

**Comment by Kenhasteandersen** [comment]
Would this do? It could go into the summary functions.

Ken

-----------------

#' Calculate the a yield curve of a species
#' 
#' Calculates the yield for a species for various values of effort for that species,
#' while the effort of the other species are kept constant.
#' 
#' @param param An object of class \code{MizerParams}.
#' @param effort A vector of effort for a species.
#' @param iSpecies The number of the species to change.
#' @param F The fishing mortalities to sweep over
#'   
#' @return An array containing the SSB (time x species)
#' @export
#' @family summary functions
#' @concept summary_function
#' 
calcYieldCurve = function(param, effort, iSpecies, F=seq(0,2,length.out = 10)) {
  yield = function(FF) {
    effort[iSpecies] = FF
    y = getYield( project(param, effort) )
    return( y[dim(y)[1],] )
  }              
  
  return( apply(as.matrix(F), 1, yield) )
  
}

**Comment by gustavdelius** [comment]
Thank you Ken. That code would calculate the yield in year 100 after the change in fishing effort starting from the current initial condition (because the default for `t_max` in `project()` is 100). Is that really what we want?

How would you use the yield curve while calibrating the model?

**Comment by gustavdelius** [comment]
Hi @Kenhasteandersen , thanks for contributing your code. I have for now moved it to the mizerExperimental package because it needs some work before it fits in nicely with the rest of mizer, see https://github.com/sizespectrum/mizerExperimental/issues/6. All non-core code that can be developed first in mizerExperimental should first be developed there.
