### ISSUE TITLE
Remove the print_it option from plots

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#62]
Does anyone remember the purpose of the `print_it = TRUE` option in the mizer plot functions? It has the effect of triggering an `print(p)` where `p` is the plot. Because the function also visibly returns the plot, in interactive use the plot gets printed anyway, even with `print_it = FALSE` and with `print_it = TRUE` it gets printed twice. 

Any objections to removing the `print_it` argument from all plot functions in order to not confuse new users and to simplify?

**Comment by juliablanchard** [comment]
Nope - sounds like a good idea to remove!

________________________________
