### ISSUE TITLE
Good colour palette for line plots

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#63]
The colour palette we are currently using is taken from http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette because it works well for colour-blind people. It looks good for area plots, for example:
![newplot](https://user-images.githubusercontent.com/1340713/60359200-40262600-99d0-11e9-9687-54ef5f8e4ab7.png)
but the palette is quite horrible for line plots, for example:
![Rplot09](https://user-images.githubusercontent.com/1340713/60359272-82e7fe00-99d0-11e9-8938-0a936d447672.png)

Does anyone know of a good colour palette to use for line plots?

**Comment by maxlindmark** [comment]
Hi,

Could the dark2 palette in RColorBrewer be an option? It allows up to 8 categories and could work even for lines against the default grey background (and colourblind friendly).

https://earlglynn.github.io/RNotes/package/RColorBrewer/index.html

Cheers

**Comment by juliablanchard** [comment]
Yes - or you can set up your own colour gradient set to the number of levels based on the number species in the model.

http://www.sthda.com/english/wiki/ggplot2-colors-how-to-change-colors-automatically-and-manually


________________________________

**Comment by gustavdelius** [comment]
@maxlindmark , @juliablanchard , thank you for your tips. These can be included in the documentation by whoever volunteers to revamps the linecolour feature as discussed in #94
