### ISSUE TITLE
Stock-recruitment relationships that include Allee effect

### ISSUE THREAD

**Issue by astaaudzi** [sizespectrum/mizer#86]
It is known that if a stock falls below a certain threshold (5-10% of virgin biomass) its recovery often can be very slow or non-existent, because Allee effects or depensation start operating at very low densities. This would not be the case with the current assumptions in mizer, because even one fish left in a population could produce millions of eggs and they all would recruit bringing abundance up rapidly again. This means that we may overestimate population recovery rates and impacts of intensive fishing. 

I am wondering whether it would make sense to allow users to setup their own SR functions, which would overwrite current SR in mizer? This way users could explore a wider range of scenarios. No need to modify the core mizer assumptions, just add flexibility

**Comment by gustavdelius** [comment]
The ability for the user to specify their own stock recruitment function has been part of mizer from the beginning. The user needs to pass their stock recruitment function via the `srr` argument in the `MizerParams()` function. Mizer also supplies three stock recruitment functions that the user can use if they do not want to write their own: `ssrBevertonHolt()`, `srrRicker()` and `srrSheperd()`. Would you like to include another function in mizer or is the facility for users to write their own function enough?

**Comment by astaaudzi** [comment]
I am not sure it is clear how to specify these relationships and I could not find anything in the MizerParams() object. Either way the question remains, because there is a potential for a lot larger number of stock-recruitment options

**Comment by gustavdelius** [comment]
@astaaudzi , the MizerParams object has always had a `srr` slot. However in the past it was not made very clear in the documentation. In the new version of mizer it is a bit better documented, see https://sizespectrum.org/mizer/dev/reference/setReproduction.html. However please try to improve the documentation further.

**Comment by gustavdelius** [comment]
@astaaudzi , do you think you need a change to mizer in order to implement a stock recruitment function with an Allee effect? If not, you can close this issue.

**Comment by astaaudzi** [comment]
@gustavdelius I think including Allee effects requires an additional parameter in the BH or Ricker recruitment functions to represent non-linearity at low stock densities (e.g. https://www.nrcresearchpress.com/doi/pdf/10.1139/f97-105 or "Depensation in fish stocks: a hierarchic Bayesian meta-analysis"). However, this can all be done in an add-on extension, so let's close the issue

**Comment by gustavdelius** [comment]
This does not even need an extension. Anyone can simply write such a
function, put its parameters into the species params data frame, and then
pass its name as the srr argument to MizerParams().
